baseURL = 'https://schuler.media/'
languageCode = 'en-us'
title = 'Schuler Media'
theme = 'minimal-llm'

[params]
  description = 'Independent Media. Strategic Storytelling.'
  author = 'Schuler Media'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
